Projetos/Canedo.Linx/Canedo.Linx.Web/Models/ErrorViewModel.cs
using System;

namespace Canedo.Linx.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projetos/Canedo.Linx/Canedo.Linx.Web/Models/IndexViewModel.cs
using Canedo.Linx.Fidelidade.Domain.Entity;
using System.Collections.Generic;

namespace Canedo.Linx.Web.Models
{
    public class IndexViewModel
    {
        public IndexViewModel()
        {
            Fidelizacoes = new List<Fidelizacao>();
        }
        public string NumeroCartao { get; set; }
        public Integracao Integracao { get; set; }
        public IEnumerable<Fidelizacao> Fidelizacoes { get; set; }
    }
}

Projetos/Canedo.Linx/Canedo.Linx.Web/Controllers/FidelidadeController.cs
using Canedo.Linx.Fidelidade.ApiService.Service;
using Canedo.Linx.Fidelidade.Data.Repository.Dapper;
using Canedo.Linx.Fidelidade.Data.Repository.EntityFramework;
using Canedo.Linx.Fidelidade.Domain.Entity;
using Canedo.Linx.Fidelidade.Domain.Model;
using Canedo.Linx.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Canedo.Linx.Web.Controllers
{
    public class FidelidadeController : Controller
    {
        readonly ConsultarFidelizacaoService consultarFidelizacaoService_;
        readonly IntegracaoDapperRepository integracaoRepository_;
        readonly FidelizacaoDapperRepository fidelizacaoRepository_;
        readonly FidelizacaoEfRepository fidelizacaoEfRepository_;
        readonly IntegracaoEfRepository integracaoEfRepository_;

        public FidelidadeController(
            ConsultarFidelizacaoService consultarFidelizacaoService, 
            IntegracaoDapperRepository integracaoRepository,
            FidelizacaoDapperRepository fidelizacaoRepository,
            FidelizacaoEfRepository fidelizacaoEfRepository,
            IntegracaoEfRepository integracaoEfRepository)
        {
            consultarFidelizacaoService_ = consultarFidelizacaoService;
            integracaoRepository_ = integracaoRepository;
            fidelizacaoRepository_ = fidelizacaoRepository;
            fidelizacaoEfRepository_ = fidelizacaoEfRepository;
            integracaoEfRepository_ = integracaoEfRepository;
        }

        // GET: Fidelidade
        public ActionResult Index()
        {
            var integracao = integracaoRepository_.GetAll().FirstOrDefault();

            

            var model = new IndexViewModel()
            {
                Integracao = integracao
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult Index(IndexViewModel indexViewModel)
        {
            var model = new ConsultaFidelizacaoBody()
            {
                NsuCliente = Guid.NewGuid().ToString(),
                ChaveIntegracao = indexViewModel.Integracao.ChaveIntegracao,
                CodigoLoja = indexViewModel.Integracao.CodigoLoja,
                NumeroCartao = indexViewModel.NumeroCartao,
                CodigoSeguranca = ""
            };

            var result = consultarFidelizacaoService_.GetConsultaFidelizacao(model);

            if (result != null)
            {
                var fidelizacao = new Fidelizacao()
                {
                    NsuCliente = new Guid(result.NsuCliente),
                    Resultado = result.Resultado,
                    SaldoEmPontos = Convert.ToInt64(result.SaldoEmPontos),
                    SaldoEmReais = Convert.ToDecimal(result.SaldoEmReais.Replace(',', '.')),
                    SaldoPontos = Convert.ToInt64(result.SaldoPontos)
                };

                fidelizacaoEfRepository_.Add(fidelizacao);

                indexViewModel.Fidelizacoes = fidelizacaoRepository_.GetAll();
            }

            UpdateIntegracao(indexViewModel);

            

            return View(indexViewModel);
        }

        private void UpdateIntegracao(IndexViewModel indexViewModel)
        {
            var dataBd = integracaoRepository_.GetById(indexViewModel.Integracao.Id);

            if (dataBd.ChaveIntegracao.Equals(indexViewModel.Integracao.ChaveIntegracao) && dataBd.CodigoLoja.Equals(indexViewModel.Integracao.CodigoLoja))
                return;

            integracaoEfRepository_.Update(indexViewModel.Integracao);
        }

        // GET: Fidelidade/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Fidelidade/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fidelidade/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Fidelidade/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Fidelidade/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Fidelidade/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Fidelidade/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projetos/Canedo.Linx/Canedo.Linx.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Canedo.Linx.Web.Models;

namespace Canedo.Linx.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projetos/Canedo.Linx/Canedo.Linx.Web/Views/Fidelidade/Index.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Fidelidade</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div class="form-group">
                <label class="control-label">Número do Cartão</label>
                <input asp-for="NumeroCartao" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Chave Integração</label>
                <input asp-for="Integracao.ChaveIntegracao" class="form-control" />
                <label class="control-label">Código Loja</label>
                <input asp-for="Integracao.CodigoLoja" class="form-control" />
                @Html.HiddenFor(s => s.Integracao.Id)
            </div>
            <div class="form-group">
                <input type="submit" value="Enviar" class="btn btn-default" />
            </div>
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nsu Cliente
                </th>
                <th>
                    Resultado
                </th>
                <th>
                    Saldo Pontos
                </th>
                <th>
                    Saldo em Pontos
                </th>
                <th>
                    Saldo em Reais
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Fidelizacoes)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NsuCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Resultado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SaldoPontos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SaldoEmPontos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SaldoEmReais)
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Projetos/Canedo.Linx/Canedo.Linx.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Projetos/Canedo.Linx/Canedo.Linx.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Canedo.Linx.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Canedo.Linx.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fidelidade" asp-action="Index">Fidelidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Canedo.Linx.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>